### ISSUE TITLE
Register game basic

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/siage#1]
Register match data and save to database.

**Comment by Andrioden** [comment]
- Input date.
- Parse date til datetime i .py
- Endre models.py Game.date til DateProperty
- Add map_type choices. Endre variablel navn til location.
- Add treaty length i gui. Endre model.Game.treath_length til IntProperty.
- Fiks team input i gui. Blank valgt betyr singel lag. Og begrens til team 1,2,3,4. Må også håndteres i backend.

**Comment by Andrioden** [comment]
- Det sendes tomme player results. Blir ikke cleaned.
