### ISSUE TITLE
Setup game - autobalance teams

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/siage#10]
Basert på rating, med noe randomness.

**Comment by bjorntore** [comment]
Subtasks:
- [SKIPPED] Andre adds a simple view to input playerlist
- [DONE] Autobalances teams.
- [DONE] Returns list of games and teams to view.

**Comment by Andrioden** [comment]
Ferdig nå med min del. Du må:
- Presenter rating dif per game og team
- legg til valg av algoritme: "random" "best_random"

**Comment by bjorntore** [comment]
Alt ferdig bortsett i fra å ta i mot verdiene i python. Knapp er disabled mens funksjonen kjører,
