### ISSUE TITLE
Decaying points for inactive players [Øyvind Bolland via mail]

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/siage#101]
Jeg søker herved om en funksjonalitet: 

Hvis en spiller ikke har vært aktiv de siste 3 gamene som registreres så blir det utdelt straff i form for poengtrekk.
Denne straffen bør være skalerbar med utgangspunkt i hvor mange games det er siden sist deltakelse.

LINÆR:
- Første runde borte mister man ingenting.
- Fra og med da så mister man 2poeng
- Til man har minimum 900.

Dvs at spiller A som ikke har vært med på de siste 12 registrerte matchene har fått følgende poengtrekk: -10, -10 ,-10, -5, -5, -5,-5,-5,-1,-1 = -57 i poeng.
Variablene for når straffen begynner og hvor stor straffen er bør kanskje kvalitetsdiskuteres. Og om det bør være et tak/bunn for hvor mye en spiller kan trekkes totalt. Dette for å unngå at neste gang han deltar så blir trekningsberegningen ikke helt opplagt.

</skikkelig formulert>

**Comment by Andrioden** [comment]
Jeg har følgende tanker:
- Hvilket problem er det vi prøver å løse her? Hva oppnår vi?
- Jeg ønsker ikke å straffe inaktivitet
- Jeg ønsker teknisk sett ikke å innføre fler kilder til point changes.

**Comment by bollizyo** [comment]
"Hvilket problem er det vi prøver å løse her? Hva oppnår vi?"
- At rankingen ikke er reell. Spillere med 0% winrate er langt over andre spillere
- At vi belønner og oppfordrer aktivitet
- At spillere som kommer tilbake fra hibernate ikke blir feilaktig plassert i forhold til sitt faktiske skillnivå.

**Comment by Andrioden** [comment]
Jeg har implementert inactive. Har vi egentlig et problem lengre?

**Comment by bollizyo** [comment]
Greit saken kan lukke tjallabais

**Comment by Andrioden** [comment]
Stemt for i en begrenset versjon:
- Kjøres en job etter hver sesjon.
- Decay fordels ut
- Decay per runde:
