### ISSUE TITLE
Register game - sort settings like ingame

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/siage#13]

**Comment by bjorntore** [comment]
http://stackoverflow.com/questions/28171380/how-to-use-choices-in-google-app-engine-ndb-model

**Comment by Andrioden** [comment]
Skal tenke på det

**Comment by Andrioden** [comment]
Jeg har lyst til å drite i dette. Det er ikke viktig og føler det blir en skitten løsning i angular. Assigner til deg, close hvis du er enig.

**Comment by bjorntore** [comment]
Setter defaultverdier til det vi bruker mest og closer
