### ISSUE TITLE
Player view - Add fun statistics

### ISSUE THREAD

**Issue by bjorntore** [Andrioden/siage#21]
Show statistics for player in the player view.
DONE - Matches played
DONE - Win percentage
DONE - Best team mate winchance
DONE - Worst team mate winchance
NOT DOING - Best team mate avg score
NOT DOING - Worst team mate avg score
DONE - Average score
DONE - Best score - show game
DONE - Worst score - show game

**Comment by bjorntore** [comment]
We should discuss how we determine Best civ/worst civ etc.

**Comment by Andrioden** [comment]
All requested stats are now availible in the GUI. But presentation table for teammate fit and civ fit is yet to be done by you BT. = )
