### ISSUE TITLE
Admin panel - For accessing the admin functions

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/siage#30]
I suggest not including it as part of the normal menu. But maybe in the top right top left or right. Bascially you should design a new "account and admin" section for the page. Like here on github on the top right. This section can contain login, logout, admin.

This task includes:
- Link to admin page in top right. is_admin variable added to the users/me api return data.
- Show button to admin functions, check the admin.py
- Add that a player claim isnt successfull until an admin has approved it.

**Comment by bjorntore** [comment]
Done

**Comment by bjorntore** [comment]
Oh, approval of claims not implemented. Assigning to André.

**Comment by Andrioden** [comment]
Have updated the api so you can now
- Find unverified players: http://localhost:8080/api/admin/unverifiedplayers/
- Verify a claim: PUT til http://localhost:8080/api/players/nick_or_id, with form data {verified: true}
- Reject a claim: PUT til http://localhost:8080/api/players/nick_or_id, with form data {userid: ""}

**Comment by Andrioden** [comment]
BT TODO: 
- oppdatere GUI sånn at register game og register player ikke vises når http://localhost:8080/api/users/me, data verified ikke er true.
- Legge til funksjonalitet for å verifisere eller avvise claim under admin.

**Comment by bjorntore** [comment]
Only missing refresh of list after claim verification or rejection
