### ISSUE TITLE
Setup game - Use "Average score" as matching criteria

### ISSUE THREAD

**Issue by Slangehiet** [Andrioden/siage#34]
When setting up teams have a small percentage be influenced by the in-game "Average Score" on the players so that the players with the highest individual scores don't end up in the same teams

**Comment by Andrioden** [comment]
I like this, it can help mix it up even better. I might use the players average score to randomize it a bit more. Meaning the teams will be auto balanced according to Rating primarily with a tiny influx from Average score.

Will test a bit and se how it works out.
