### ISSUE TITLE
Player view - Show recent games

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/siage#37]
Show last games played like the league table. Change api/games query to accept player filter, match count filter.

Also show rating earned in the recent games list with green/red indication.

**Comment by Andrioden** [comment]
I decided to solve this by simply returning a games list in the player/id api call. If we need/want the api/games list to be able to return and filter on player id I can revisit the problem.

Arguments for returning games data with player data:
- Less overhead on calls to db.
- Easier

Argument against:
- Less clean api.

**Comment by Andrioden** [comment]
api/games now takes player_id post data. Example call:

http://localhost:8080/api/games/?max=1&player_id=5348024557502464

**Comment by bjorntore** [comment]
Include players rating after match in the api/games/player_id=x result.
Will use this to create rating change timeline foir player.

**Comment by Andrioden** [comment]
Done, returned as stats_rating

**Comment by bjorntore** [comment]
Showing basic graph of rating history in player view.
