### ISSUE TITLE
Admin page - Error messages is not replaced when successfulll

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/siage#58]
1. Go to admin page
2. Change source code to throw error for api call
3. Call the api and get an error
4. Remove source code throw
5. Call the api again and se that the error message is not replaced

**Comment by Andrioden** [comment]
Jeg er har nå oppdatert api sånn at man kan:

- Finn uverifisert: http://localhost:8080/api/admin/unverifiedplayers/
- Verifisere spiller: PUT til http://localhost:8080/api/players/nick_or_id, med form data {verified: true}
- Avvise claim: PUT til http://localhost:8080/api/players/nick_or_id, med form data {userid: ""}

**Comment by bjorntore** [comment]
#critical #Fixnow :P
