### ISSUE TITLE
Rating graph links is not angular friendly links

### ISSUE THREAD

**Issue by Andrioden** [Andrioden/siage#81]
The page is reloaded, instead of navigated as a single page.

**Comment by bjorntore** [comment]
Vet, men fikk ikke til å execute angular redirect derfra. Skal prøve igjen.

**Comment by bjorntore** [comment]
done... https://github.com/Andrioden/siage/commit/3b0046f74a17b7e9ff9a6b4ec67f5a898a1b4561
